# This is a basic workflow to help you get started with Actions

name: Unit Test (Ubuntu latest)

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Test FADe (Phase 1-1 / normal type (self packaged))
      run: |
        sudo npm install -g typescript
        yarn install
        tsc
        COMMIT=$(git rev-parse HEAD | head -c 7)
        node dist/ --init --path . --name fade --version 0.0.0-$COMMIT --description "A project which everyone can make linux package easily" --url "https://github.com/fade-project/fade" --priority optional --architecture all --cmdline "node dist/" --dependency nodejs --maintainer-name "FADe Project" --maintainer-email "fade-linux@protonmail.com" --type normal --blacklist .fadework/ --blacklist .git/
        node dist/ --create-deb --path .

    - name: Test FADe (Phase 1-2 / Upload to GitHub Artifact)
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Debian Package (normal, self)
        # A file, directory or wildcard pattern that describes what to upload
        path: fade_0.0.0-*_all.deb
  
    - name: Test FADe (Phase 1-3 / normal type (self packaged))
      run: |
        COMMIT=$(git rev-parse HEAD | head -c 7)
        sudo dpkg --ignore-depends=nodejs -i fade_0.0.0-$COMMIT\_all.deb
        fade moo

    - name: Test FADe (Phase 2-1 / isolated type (self packaged))
      run: |
        git clean -df
        git reset --hard
        rm -rf .fadework
        yarn install
        tsc
        COMMIT=$(git rev-parse HEAD | head -c 7)
        node dist/ --init --path . --name fade --version 0.0.0-$COMMIT-isolated --description "A project which everyone can make linux package easily" --url "https://github.com/fade-project/fade" --priority optional --architecture all --cmdline "node dist/" --dependency nodejs --maintainer-name "FADe Project" --maintainer-email "fade-linux@protonmail.com" --type isolated --blacklist .fadework/ --blacklist .git/
        node dist/ --create-deb --path .

    - name: Test FADe (Phase 2-2 / Upload to GitHub Artifact)
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Debian Package (isolated, self)
        # A file, directory or wildcard pattern that describes what to upload
        path: fade_0.0.0-*_all.deb

    - name: Test FADe (Phase 2-3 / isolated type (self packaged))
      run: |
        COMMIT=$(git rev-parse HEAD | head -c 7)
        sudo dpkg --ignore-depends=nodejs -i fade_0.0.0-$COMMIT-isolated_all.deb
        fade moo

    - name: Test FADe (Phase 3-1 / symlink type (self packaged))
      run: |
        git clean -df
        git reset --hard
        rm -rf .fadework
        yarn install
        tsc
        chmod 0755 dist/index.js
        sed -i '1i #!/usr/bin/env node' dist/index.js
        COMMIT=$(git rev-parse HEAD | head -c 7)
        node dist/ --init --path . --name fade --version 0.0.0-$COMMIT-symlink --description "A project which everyone can make linux package easily" --url "https://github.com/fade-project/fade" --priority optional --architecture all --cmdline "dist/index.js" --dependency nodejs --maintainer-name "FADe Project" --maintainer-email "fade-linux@protonmail.com" --type symlink --blacklist .fadework/ --blacklist .git/
        node dist/ --create-deb --path .

    - name: Test FADe (Phase 3-2 / Upload to GitHub Artifact)
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Debian Package (symlink, self)
        # A file, directory or wildcard pattern that describes what to upload
        path: fade_0.0.0-*_all.deb

    - name: Test FADe (Phase 3-3 / symlink type (self packaged))
      run: |
        COMMIT=$(git rev-parse HEAD | head -c 7)
        sudo dpkg --ignore-depends=nodejs -i fade_0.0.0-$COMMIT-symlink_all.deb
        fade moo

    - name: Test FADe (Phase 4-1 / service type (Dummy Service))
      run: |
        COMMIT=$(git rev-parse HEAD | head -c 7)
        git clone https://github.com/ldmsys/dummy-node-service
        node dist/ --init --path dummy-node-service --name dummy-node-service --version 0.0.0-$COMMIT-dummy --description "Test" --url "https://github.com/ldmsys/dummy-node-service" --cmdline "node main.js" --dependency nodejs --maintainer-name "ldmsys" --maintainer-email "admin@ldmsys.net" --type service
        node dist/ --create-deb --path ./dummy-node-service --output dummy-node-service_0.0.0-$COMMIT-dummy_all.deb
    
    - name: Test FADe (Phase 4-2 / Upload to GitHub Artifact)
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Debian Package (service, dummy)
        # A file, directory or wildcard pattern that describes what to upload
        path: dummy-node-service_0.0.0-*_all.deb

    - name: Test FADe (Phase 4-3 / isolated type (self packaged))
      run: |
        COMMIT=$(git rev-parse HEAD | head -c 7)
        sudo dpkg --ignore-depends=nodejs -i dummy-node-service_0.0.0-$COMMIT-dummy_all.deb
        systemctl status dummy-node-service

    - name: Test FADe (Phase 4-4 / Remove Test)
      run: |
        sudo dpkg -P dummy-node-service

    - name: Create Compiled JS File
      run: |
        cd $GITHUB_WORKSPACE
        sudo npm install -g @vercel/ncc
        ncc build dist/ -o ncced -m
    # Runs a set of commands using the runners shell
    - name: Create Static Binary
      run: |
        cd $GITHUB_WORKSPACE
        npm install
        sudo npm install -g pkg
        pkg .
    
    - name: Upload Static Binary
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Static Binary
        # A file, directory or wildcard pattern that describes what to upload
        path: fade-*

    - name: Upload Compiled JS File
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Compiled JS
        # A file, directory or wildcard pattern that describes what to upload
        path: dist/*